name: Test on Push

on:
    push:
        branches:
            - main
    [pull_request, issues]


jobs:
  test:
    name: Test on push
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: actions-notifyer
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
