name: Test on Push
on:
    push:
        branches:
            - main
jobs:
    test:
        name: Test on push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
                coverage: none
                tools: cs2pr
                extensions: ctype, dom, gd, iconv, fileinfo, libxml, mbstring, simplexml, xml, xmlreader, xmlwriter, zip, zlib

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir --working-dir=app/plugins)" >> $GITHUB_OUTPUT

            - name: Configure Composer cache
              uses: actions/cache@v3.2.4
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: composer install --working-dir=app/plugins --prefer-dist --optimize-autoloader --no-progress --no-interaction --no-dev --no-plugins --no-scripts

            - name: Validate composer.json
              run: composer --working-dir=app/plugins --no-interaction validate --no-check-all

            - name: List installed composer packages
              run: composer --working-dir=app/plugins show -i -t

            - name: Slack Notify
              uses: rtCamp/action-slack-notify@master
              env:
                SLACK_CHANNEL: actions-notifyer
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
